# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: ai-banking-service
spec:
  selector:
    app: ai-banking-app
  ports:
  - name: frontend
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: bankapp-backend
spec:
  selector:
    app: ai-banking-app
  ports:
  - name: backend
    port: 5000
    targetPort: 5000
  type: ClusterIP

---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
