apiVersion: v1

kind: Service

metadata:
  name: ai-banking-service

spec:
  selector:
    app: ai-banking-app
  ports:
  - name: frontend
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: backend
    port: 5000
    targetPort: 5000
    nodePort: 30500
  type: NodePort
