pipeline {
    agent any
    
    stages {
        stage("Code Clone") {
            steps {
                echo "this is cloning the code"
                git url: "https://github.com/dilnawaj9128/AI-Banking-App.git", branch:"main"
                echo "code cloning successful"
            }
        }
        stage("build docker image"){
            parallel {
                stage('build backend'){
                    steps{
                        sh 'docker build -t ai-banking-app-backend:latest ./backend'
                    }
                }
                stage("build frontend"){
                    steps{
                        sh 'docker build -t ai-banking-app-frontend:latest ./frontend'
                    }
                }
            }
        }
        stage('🔍 Security Scan') {
            steps {
                sh "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image ai-banking-app-backend:latest --severity HIGH,CRITICAL --exit-code 0"
                sh "docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image ai-banking-app-frontend:latest --severity HIGH,CRITICAL --exit-code 0"
                echo "✅ Security scan complete"
            }
        }
        
        stage("Push to DockerHub"){
            steps{
                echo "This is Pshing The Image to Docker Hub"
                withCredentials([usernamePassword(
                    credentialsId:"dockerHubCred",
                    passwordVariable:"dockerHubPass",
                    usernameVariable:"dockerHubUser")]){
                sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPass} "
                sh "docker image tag ai-banking-app-backend:latest ${env.dockerHubUser}/ai-banking-app-backend:latest"
                sh "docker image tag ai-banking-app-frontend:latest ${env.dockerHubUser}/ai-banking-app-frontend:latest"
                sh "docker push ${env.dockerHubUser}/ai-banking-app-backend:latest"
                sh "docker push ${env.dockerHubUser}/ai-banking-app-frontend:latest"
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                    kubectl apply -f k8s/deployment.yml
                    kubectl apply -f k8s/service.yml
                    kubectl rollout restart deployment/ai-banking-app
                    kubectl rollout status deployment/ai-banking-app --timeout=120s
                '''
            }
        }
        stage('Health Check') {
            steps {
                sleep(time: 15, unit: 'SECONDS')
                sh "kubectl get pods"
                echo "All pods running"
            }
        }
    }
    post {
        success {
            echo "Pipeline SUCCESS - Build deployed"
        }
        failure {
            echo "Pipeline FAILED - Check logs above"
        }
    }
}    
